name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Étape 1: Checkout du code
    - name: Checkout code
      uses: actions/checkout@v2

    # Étape 2: Configuration de Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    # Étape 3: Installer les dépendances
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Étape 4: Exécuter les tests
    - name: Run tests
      run: |
        pytest tests/
